# Panda

### This notebook is created for my learning Panda with the help of course provide by Kaggle

# Topic 1 : Creating, Reading and Writing

In [1]:
#Import Pandas library

import pandas as pd

There are two core objective in pandas:
 * Data frame
 * Series
 
#### Data Frame
 Tables structure with rows and column

#### Series
 * Sequence of data values
 * its a Series is a list
 * Series is a single column of a DataFrame
 * Assign column values to the Series the same way as before, using an index parameter
 * However, a Series does not have a column name, it only has one overall name

### Creating Data Frame

In [2]:
pd.DataFrame({'yes':[5,6],"no":[3,4]})

   yes  no
0    5   3
1    6   4

In [3]:
# with index define
pd.DataFrame({'yes':[5,6],"no":[3,4]},index=["Respose 1","Respose 2"])

           yes  no
Respose 1    5   3
Respose 2    6   4

### Creating Series

In [4]:
pd.Series([1,23,33,4,56,7])

0     1
1    23
2    33
3     4
4    56
5     7
dtype: int64

In [5]:
pd.Series([1,23,345,456],index=["val1","val2","val3","val4"],name="ValuesList")

val1      1
val2     23
val3    345
val4    456
Name: ValuesList, dtype: int64

## Reading Data

In [6]:
# Wine review Source Kaggle
# Assign first col as index 
wine_reviews = pd.read_csv("./data/winemag-data_first150k.csv",index_col=0)

In [7]:
# Shape of data to check the size of file
wine_reviews.shape

(150930, 10)

In [8]:
# screening the data
wine_reviews.head()

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude

In [9]:
# Saving to csv
dataCsv =pd.DataFrame({'yes':[5,6],"no":[3,4]},index=["Respose 1","Respose 2"])

dataCsv.to_csv("Savefile.csv")

# Topic 2 : Index,Selecting & Assigning

* Column : Access the property of an object by accessing it as an attribute.

In [10]:
wine_reviews.country

0             US
1          Spain
2             US
3             US
4         France
           ...
150925     Italy
150926    France
150927     Italy
150928    France
150929     Italy
Name: country, Length: 150930, dtype: object

 * We can asses its values using the indexing operator

In [11]:
wine_reviews["country"]

0             US
1          Spain
2             US
3             US
4         France
           ...
150925     Italy
150926    France
150927     Italy
150928    France
150929     Italy
Name: country, Length: 150930, dtype: object

In [12]:
wine_reviews.country[0]

'US'

In [13]:
wine_reviews['country'][0]

'US'

## Indexing

Index based selection
* First row then column (This is the opposite of what we do in native Python, which is column-first, row-second)
* iloc : on its numeric positions

In [14]:
wine_reviews.iloc[0]

country                                                       US
description    This tremendous 100% varietal wine hails from ...
designation                                    Martha's Vineyard
points                                                        96
price                                                        235
province                                              California
region_1                                             Napa Valley
region_2                                                    Napa
variety                                       Cabernet Sauvignon
winery                                                     Heitz
Name: 0, dtype: object

In [15]:
wine_reviews.iloc[[1,2],1]

1    Ripe aromas of fig, blackberry and cassis are ...
2    Mac Watson honors the memory of a wine once ma...
Name: description, dtype: object

Label-Based Selection
 * .loc: the data index value, not its position

In [16]:
wine_reviews.loc[0,"country"]

'US'

In [17]:
wine_reviews.loc[0,:]

country                                                       US
description    This tremendous 100% varietal wine hails from ...
designation                                    Martha's Vineyard
points                                                        96
price                                                        235
province                                              California
region_1                                             Napa Valley
region_2                                                    Napa
variety                                       Cabernet Sauvignon
winery                                                     Heitz
Name: 0, dtype: object

* iloc uses the Python stdlib indexing scheme, where the first element of the range is included and the last one excluded.So 0:10 will select entries 0,...,9. 
* loc, meanwhile, indexes inclusively. So 0:10 will select entries 0,...,10.

### Manipulation Index

In [18]:
wine_reviews.set_index("country")

,description,designation,points,price,province,region_1,region_2,variety,winery
country,,,,,,,,,
US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude
...,...,...,...,...,...,...,...,...,...
Italy,Many people feel Fiano represents southern Ita...,NaN,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio
France,"Offers an intriguing nose with ginger, lime an...",Cuvée Prestige,91,27.0,Champagne,Champagne,NaN,Champagne Blend,H.Germain
Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora
France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset
Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

##### Q : If wine is italian or not

In [19]:
wine_reviews.loc[wine_reviews.country=="Italy"].head() #head rows

,country,description,designation,points,price,province,region_1,region_2,variety,winery
10,Italy,"Elegance, complexity and structure come togeth...",Ronco della Chiesa,95,80.0,Northeastern Italy,Collio,NaN,Friulano,Borgo del Tiglio
32,Italy,"Underbrush, scorched earth, menthol and plum s...",Vigna Piaggia,90,NaN,Tuscany,Brunello di Montalcino,NaN,Sangiovese,Abbadia Ardenga
35,Italy,"Forest floor, tilled soil, mature berry and a ...",Riserva,90,135.0,Tuscany,Brunello di Montalcino,NaN,Sangiovese,Carillon
37,Italy,"Aromas of forest floor, violet, red berry and ...",NaN,90,29.0,Tuscany,Vino Nobile di Montepulciano,NaN,Sangiovese,Avignonesi
38,Italy,"This has a charming nose that boasts rose, vio...",NaN,90,23.0,Tuscany,Chianti Classico,NaN,Sangiovese,Casina di Cornia

#### Q if wine is italian or not AND points at least 90

In [20]:
wine_reviews.loc[(wine_reviews.country=="Italy") & (wine_reviews.points >= 90)].head() # head row

,country,description,designation,points,price,province,region_1,region_2,variety,winery
10,Italy,"Elegance, complexity and structure come togeth...",Ronco della Chiesa,95,80.0,Northeastern Italy,Collio,NaN,Friulano,Borgo del Tiglio
32,Italy,"Underbrush, scorched earth, menthol and plum s...",Vigna Piaggia,90,NaN,Tuscany,Brunello di Montalcino,NaN,Sangiovese,Abbadia Ardenga
35,Italy,"Forest floor, tilled soil, mature berry and a ...",Riserva,90,135.0,Tuscany,Brunello di Montalcino,NaN,Sangiovese,Carillon
37,Italy,"Aromas of forest floor, violet, red berry and ...",NaN,90,29.0,Tuscany,Vino Nobile di Montepulciano,NaN,Sangiovese,Avignonesi
38,Italy,"This has a charming nose that boasts rose, vio...",NaN,90,23.0,Tuscany,Chianti Classico,NaN,Sangiovese,Casina di Cornia

Suppose we'll buy any wine that's made in Italy or which is rated above average. For this we use a pipe (|)

In [21]:
wine_reviews.loc[(wine_reviews.country=="Italy") | (wine_reviews.points >= 90)].head() # head rows

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude

In [22]:
# isin  : in List 

wine_reviews.loc[wine_reviews.country.isin(['Italy', 'France'])].head() # head rows

,country,description,designation,points,price,province,region_1,region_2,variety,winery
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude
10,Italy,"Elegance, complexity and structure come togeth...",Ronco della Chiesa,95,80.0,Northeastern Italy,Collio,NaN,Friulano,Borgo del Tiglio
13,France,This wine is in peak condition. The tannins an...,Château Montus Prestige,95,90.0,Southwest France,Madiran,NaN,Tannat,Vignobles Brumont
18,France,Coming from a seven-acre vineyard named after ...,Le Pigeonnier,95,290.0,Southwest France,Cahors,NaN,Malbec,Château Lagrézette
32,Italy,"Underbrush, scorched earth, menthol and plum s...",Vigna Piaggia,90,NaN,Tuscany,Brunello di Montalcino,NaN,Sangiovese,Abbadia Ardenga

In [23]:
# isnull & notnull

wine_reviews.loc[wine_reviews.region_1.isnull()].head() # head rows

,country,description,designation,points,price,province,region_1,region_2,variety,winery
25,New Zealand,"Yields were down in 2015, but intensity is up,...",Maté's Vineyard,94,57.0,Kumeu,NaN,NaN,Chardonnay,Kumeu River
30,Bulgaria,This Bulgarian Mavrud presents the nose with s...,Bergulé,90,15.0,Bulgaria,NaN,NaN,Mavrud,Villa Melnik
42,US,This is an aromatic brooder with aromas of sco...,Private Reserve,90,55.0,Idaho,NaN,NaN,Petite Sirah,Huston
64,Portugal,"This is a super-ripe, still very young wine. I...",NaN,91,23.0,Alentejano,NaN,NaN,Portuguese Red,Herdade do Rocim
74,Portugal,It is the ripe dark Alicante Bouschet that dom...,Premium,91,15.0,Alentejo,NaN,NaN,Portuguese Red,Adega Cooperativa de Borba

### Assign Data

In [24]:
wine_reviews['index_backwards'] = range(len(wine_reviews), 0, -1)

In [25]:
wine_reviews.loc[:,'index_backwards'].head()

0    150930
1    150929
2    150928
3    150927
4    150926
Name: index_backwards, dtype: int32

In [26]:
 # country Australia or Newsland with points at least 95
wine_reviews.loc[(wine_reviews.country.isin(["Australia","New Zealand"])) & (wine_reviews.points >=95)]

,country,description,designation,points,price,province,region_1,region_2,variety,winery,index_backwards
2148,Australia,Full-bodied and plush yet vibrant and imbued w...,The Factor,98,125.0,South Australia,Barossa Valley,NaN,Shiraz,Torbreck,148782
2458,Australia,This is a top example of the classic Australia...,The Peake,96,150.0,South Australia,McLaren Vale,NaN,Cabernet-Shiraz,Hickinbotham,148472
3033,Australia,This Cabernet equivalent to Grange has explode...,Bin 707,95,500.0,South Australia,South Australia,NaN,Cabernet Sauvignon,Penfolds,147897
3044,Australia,"From vines planted in 1912, this has been an i...",Mount Edelstone Vineyard,95,200.0,South Australia,Eden Valley,NaN,Shiraz,Henschke,147886
3047,Australia,"This is a throwback to those brash, flavor-exu...",One,95,95.0,South Australia,Langhorne Creek,NaN,Red Blend,Heartland,147883
...,...,...,...,...,...,...,...,...,...,...,...
122779,Australia,If Standish's Relic is the feminine side of Sh...,The Standish Single Vineyard,96,135.0,South Australia,Barossa Valley,NaN,Shiraz,Standish,28151
127614,Australia,This stellar wine takes a little time in the g...,Hill of Grace,95,625.0,South Australia,Eden Valley,NaN,Shiraz,Henschke,23316
137383,Australia,The 2007 Astralis impresses for its combinatio...,Astralis,95,225.0,South Australia,Clarendon,NaN,Syrah,Clarendon Hills,13547
150562,Australia,"As unevolved as they are, the dense and multil...",Grange,96,185.0,South Australia,South Australia,NaN,Shiraz,Penfolds,368
150563,Australia,"Seamless luxury from stem to stern, this ‘baby...",RWT,95,70.0,South Australia,Barossa Valley,NaN,Shiraz,Penfolds,367

## Topic 3 : Summary, Function, Map

### Summary Function

In [27]:
wine_reviews.points.describe()

count    150930.000000
mean         87.888418
std           3.222392
min          80.000000
25%          86.000000
50%          88.000000
75%          90.000000
max         100.000000
Name: points, dtype: float64

In [28]:
wine_reviews.country.describe()

count     150925
unique        48
top           US
freq       62397
Name: country, dtype: object

In [29]:
wine_reviews.points.mean()

87.8884184721394

In [30]:
wine_reviews.country.unique()

array(['US', 'Spain', 'France', 'Italy', 'New Zealand', 'Bulgaria',
       'Argentina', 'Australia', 'Portugal', 'Israel', 'South Africa',
       'Greece', 'Chile', 'Morocco', 'Romania', 'Germany', 'Canada',
       'Moldova', 'Hungary', 'Austria', 'Croatia', 'Slovenia', nan,
       'India', 'Turkey', 'Macedonia', 'Lebanon', 'Serbia', 'Uruguay',
       'Switzerland', 'Albania', 'Bosnia and Herzegovina', 'Brazil',
       'Cyprus', 'Lithuania', 'Japan', 'China', 'South Korea', 'Ukraine',
       'England', 'Mexico', 'Georgia', 'Montenegro', 'Luxembourg',
       'Slovakia', 'Czech Republic', 'Egypt', 'Tunisia', 'US-France'],
      dtype=object)

In [31]:
wine_reviews.country.value_counts()

US                        62397
Italy                     23478
France                    21098
Spain                      8268
Chile                      5816
Argentina                  5631
Portugal                   5322
Australia                  4957
New Zealand                3320
Austria                    3057
Germany                    2452
South Africa               2258
Greece                      884
Israel                      630
Hungary                     231
Canada                      196
Romania                     139
Slovenia                     94
Uruguay                      92
Croatia                      89
Bulgaria                     77
Moldova                      71
Mexico                       63
Turkey                       52
Georgia                      43
Lebanon                      37
Cyprus                       31
Brazil                       25
Macedonia                    16
Serbia                       14
Morocco                      12
Luxembourg                    9
England                       9
India                         8
Lithuania                     8
Czech Republic                6
Ukraine                       5
Bosnia and Herzegovina        4
Switzerland                   4
South Korea                   4
Slovakia                      3
Egypt                         3
China                         3
Japan                         2
Tunisia                       2
Albania                       2
Montenegro                    2
US-France                     1
Name: country, dtype: int64

### Maps

there are two mapping method:
* map() : should expect a single value from the Series
* apply() : the equivalent method if we want to transform a whole DataFrame

In [32]:
meanreview=wine_reviews.points.mean()
wine_reviews.points.map(lambda a:a - meanreview)

0         8.111582
1         8.111582
2         8.111582
3         8.111582
4         7.111582
            ...
150925    3.111582
150926    3.111582
150927    3.111582
150928    2.111582
150929    2.111582
Name: points, Length: 150930, dtype: float64

In [33]:
def remean_points(row):
    row.points = row.points - meanreview
    return row

In [34]:
wine_reviews.apply(remean_points, axis='columns')

,country,description,designation,points,price,province,region_1,region_2,variety,winery,index_backwards
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,8.111582,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz,150930
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,8.111582,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez,150929
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,8.111582,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley,150928
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,8.111582,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi,150927
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,7.111582,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude,150926
...,...,...,...,...,...,...,...,...,...,...,...
150925,Italy,Many people feel Fiano represents southern Ita...,NaN,3.111582,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio,5
150926,France,"Offers an intriguing nose with ginger, lime an...",Cuvée Prestige,3.111582,27.0,Champagne,Champagne,NaN,Champagne Blend,H.Germain,4
150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,3.111582,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora,3
150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,2.111582,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset,2
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,2.111582,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder,1

## Topic 4 : Grouping  and Sorting

In [35]:
# Group by 
#Groupby() created a group of COUNTRY COUNT.
wine_reviews.groupby('country').country.count().head()

country
Albania                      2
Argentina                 5631
Australia                 4957
Austria                   3057
Bosnia and Herzegovina       4
Name: country, dtype: int64

In [36]:
# First row of each slice group 
wine_reviews.groupby('country').apply(lambda df: df.winery.iloc[0]).head() #head rows

country
Albania                                 Arbëri
Argentina                    Matias Riccitelli
Australia                            Moorooduc
Austria                   Johanneshof Reinisch
Bosnia and Herzegovina           Winery Čitluk
dtype: object

In [37]:
wine_reviews.groupby(['country', 'winery']).apply(lambda df: df.loc[df.points.idxmax()])

                                   country  \
country   winery
Albania   Arbëri                   Albania
Argentina 1919                   Argentina
          2 Copas                Argentina
          25 Lagunas             Argentina
          Achaval-Ferrer         Argentina
...                                    ...
Uruguay   Pisano Arretxea          Uruguay
          Tanterra                 Uruguay
          Toscanini                Uruguay
          Vinson Richards          Uruguay
          Viñedo de los Vientos    Uruguay

                                                                       description  \
country   winery
Albania   Arbëri                 This garnet-colored wine made from 100% Kallme...
Argentina 1919                   Black cherry mixes with raisin on the dark, me...
          2 Copas                Smells like wet dog, with sweaty red fruit. Th...
          25 Lagunas             Sharp berry and cherry aromas are like nail po...
          Achaval-Ferrer         Dusty cherry, wild berry and minerally aromas ...
...                                                                            ...
Uruguay   Pisano Arretxea        Ripe aromas of raisin and cassis come with cre...
          Tanterra               There's a disjointed layer of vanilla hovering...
          Toscanini              Earth, saddle leather and roasted berry aromas...
          Vinson Richards        Inky and saturated in the nose, with aromas of...
          Viñedo de los Vientos  Very expensive for a novelty, and without comi...

                                                     designation  points  \
country   winery
Albania   Arbëri                                             NaN      88
Argentina 1919                                               NaN      85
          2 Copas                                            NaN      81
          25 Lagunas                                         NaN      81
          Achaval-Ferrer                       Finca Bella Vista      93
...                                                          ...     ...
Uruguay   Pisano Arretxea           Estate Bottled Grand Reserve      88
          Tanterra                                           NaN      84
          Toscanini                            Adagio Espressivo      86
          Vinson Richards                                Reserve      86
          Viñedo de los Vientos  Angel's Cuvée Ripasso de Tannat      81

                                 price          province       region_1  \
country   winery
Albania   Arbëri                  20.0           Mirditë            NaN
Argentina 1919                    10.0  Mendoza Province        Mendoza
          2 Copas                  8.0  Mendoza Province        Mendoza
          25 Lagunas              10.0             Other       San Juan
          Achaval-Ferrer         140.0  Mendoza Province  Luján de Cuyo
...                                ...               ...            ...
Uruguay   Pisano Arretxea         46.0          Progreso            NaN
          Tanterra                19.0          San Jose            NaN
          Toscanini               30.0         Canelones            NaN
          Vinson Richards         17.0           Juanico            NaN
          Viñedo de los Vientos   59.0         Atlantida            NaN

                                region_2             variety  \
country   winery
Albania   Arbëri                     NaN             Kallmet
Argentina 1919                       NaN              Malbec
          2 Copas                    NaN           Red Blend
          25 Lagunas                 NaN  Cabernet Sauvignon
          Achaval-Ferrer             NaN              Malbec
...                                  ...                 ...
Uruguay   Pisano Arretxea            NaN           Red Blend
          Tanterra                   NaN        Tannat-Syrah
          Toscanini                  NaN           Red Blend
          Vinson Richards            NaN              Tannat
          Viñedo de los Vientos      NaN              Tannat

                                                winery  index_backwards
country   winery
Albania   Arbëri                                Arbëri           146288
Argentina 1919                                    1919             1477
          2 Copas                              2 Copas           104146
          25 Lagunas                        25 Lagunas           122333
          Achaval-Ferrer                Achaval-Ferrer           143616
...                                                ...              ...
Uruguay   Pisano Arretxea              Pisano Arretxea           142797
          Tanterra                            Tanterra           105507
          Toscanini                          Toscanini            80771
          Vinson Richards              Vinson Richards             7851
          Viñedo de los Vientos  Viñedo de los Vientos            80764

[14994 rows x 11 columns]

## Sorting

In [38]:
wine_reviews.sort_values(by="price").head()

,country,description,designation,points,price,province,region_1,region_2,variety,winery,index_backwards
90546,Argentina,Clean as anyone should reasonably expect given...,NaN,85,4.0,Mendoza Province,Mendoza,NaN,Malbec,Toca Diamonte,60384
25645,US,"There's a lot going on in this Merlot, which i...",NaN,86,4.0,California,California,California Other,Merlot,Bandit,125285
118347,US,"Light and earthy, this wine-in-a-box is clean ...",NaN,84,4.0,California,California,California Other,Cabernet Sauvignon,Bandit,32583
1858,US,"Sweet and fruity, this canned wine feels soft ...",Unoaked,83,4.0,California,California,California Other,Chardonnay,Pam's Cuties,149072
91766,Argentina,"Crimson in color but also translucent, with a ...",Red,84,4.0,Mendoza Province,Mendoza,NaN,Malbec-Syrah,Broke Ass,59164

In [39]:
wine_reviews.sort_values(by="price",ascending=False).head()

,country,description,designation,points,price,province,region_1,region_2,variety,winery,index_backwards
34920,France,"A big, powerful wine that sums up the richness...",NaN,99,2300.0,Bordeaux,Pauillac,NaN,Bordeaux-style Red Blend,Château Latour,116010
13318,US,The nose on this single-vineyard wine from a s...,Roger Rose Vineyard,91,2013.0,California,Arroyo Seco,Central Coast,Chardonnay,Blair,137612
34922,France,"A massive wine for Margaux, packed with tannin...",NaN,98,1900.0,Bordeaux,Margaux,NaN,Bordeaux-style Red Blend,Château Margaux,116008
26296,France,A wine that has created its own universe. It h...,Clos du Mesnil,100,1400.0,Champagne,Champagne,NaN,Chardonnay,Krug,124634
51886,France,A wine that has created its own universe. It h...,Clos du Mesnil,100,1400.0,Champagne,Champagne,NaN,Chardonnay,Krug,99044

In [40]:
# sort by more than one column
wine_reviews.sort_values(by=['country', 'price']).head()

,country,description,designation,points,price,province,region_1,region_2,variety,winery,index_backwards
4642,Albania,This garnet-colored wine made from 100% Kallme...,NaN,88,20.0,Mirditë,NaN,NaN,Kallmet,Arbëri,146288
4864,Albania,This garnet-colored wine made from 100% Kallme...,NaN,88,20.0,Mirditë,NaN,NaN,Kallmet,Arbëri,146066
36716,Argentina,"Crimson in color but also translucent, with a ...",Red,84,4.0,Mendoza Province,Mendoza,NaN,Malbec-Syrah,Broke Ass,114214
90546,Argentina,Clean as anyone should reasonably expect given...,NaN,85,4.0,Mendoza Province,Mendoza,NaN,Malbec,Toca Diamonte,60384
91766,Argentina,"Crimson in color but also translucent, with a ...",Red,84,4.0,Mendoza Province,Mendoza,NaN,Malbec-Syrah,Broke Ass,59164

In [41]:
wine_reviews.groupby('price').points.max().sort_index()

price
4.0        86
5.0        90
6.0        90
7.0        90
8.0        91
         ...
1300.0     96
1400.0    100
1900.0     98
2013.0     91
2300.0     99
Name: points, Length: 357, dtype: int64

## Topic 5 : Data Typed and Missing Values

### Dtype grabs the type of a specific column

In [48]:
wine_reviews.price.dtype

dtype('float64')

In [50]:
# for every column

wine_reviews.dtypes

country             object
description         object
designation         object
points               int64
price              float64
province            object
region_1            object
region_2            object
variety             object
winery              object
index_backwards      int32
dtype: object

In [53]:
#convert type
wine_reviews.points.astype('float64')

0         96.0
1         96.0
2         96.0
3         96.0
4         95.0
          ...
150925    91.0
150926    91.0
150927    91.0
150928    90.0
150929    90.0
Name: points, Length: 150930, dtype: float64

### Missing Data

* pd.isnull()
* pd.notnull()

In [57]:
# find column with missing country

wine_reviews[wine_reviews.country.isnull()].head() # Head rows

,country,description,designation,points,price,province,region_1,region_2,variety,winery,index_backwards
1133,NaN,Delicate white flowers and a spin of lemon pee...,Askitikos,90,17.0,NaN,NaN,NaN,Assyrtiko,Tsililis,149797
1440,NaN,"A blend of 60% Syrah, 30% Cabernet Sauvignon a...",Shah,90,30.0,NaN,NaN,NaN,Red Blend,Büyülübağ,149490
68226,NaN,"From first sniff to last, the nose never makes...",Piedra Feliz,81,15.0,NaN,NaN,NaN,Pinot Noir,Chilcas,82704
113016,NaN,"From first sniff to last, the nose never makes...",Piedra Feliz,81,15.0,NaN,NaN,NaN,Pinot Noir,Chilcas,37914
135696,NaN,"From first sniff to last, the nose never makes...",Piedra Feliz,81,15.0,NaN,NaN,NaN,Pinot Noir,Chilcas,15234

In [62]:
# fill null value with 'Unknown'
wine_reviews.region_1.fillna("Unknown").head()

0          Napa Valley
1                 Toro
2       Knights Valley
3    Willamette Valley
4               Bandol
Name: region_1, dtype: object

In [63]:
# Replace Value
wine_reviews.country.replace("US","USA").head()

0       USA
1     Spain
2       USA
3       USA
4    France
Name: country, dtype: object

In [64]:
wine_reviews.price.isnull().count()

150930

In [68]:
wine_reviews.price[pd.isnull(wine_reviews.price)].count()

0

In [71]:
wine_reviews.region_1.fillna('Unknown').value_counts(ascending=True)

Unknown                                  25060
Napa Valley                               6209
Columbia Valley (WA)                      4975
Mendoza                                   3586
Russian River Valley                      3571
                                         ...
Ventura County                               1
Central Valley                               1
San Luis Obispo-Sonoma-Monterey              1
Muscadet Sèvre et Maine Clisson              1
Recioto della Valpolicella Valpantena        1
Name: region_1, Length: 1237, dtype: int64

## Topic 6: Renaming & Combining

#### Renaming

In [73]:
wine_reviews.rename(columns={'points':"score"}).head() # head row

,country,description,designation,score,price,province,region_1,region_2,variety,winery,index_backwards
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz,150930
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez,150929
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley,150928
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi,150927
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude,150926

In [74]:
# rename index
wine_reviews.rename(index={0: 'firstEntry', 1: 'secondEntry'}).head()

,country,description,designation,points,price,province,region_1,region_2,variety,winery,index_backwards
firstEntry,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz,150930
secondEntry,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez,150929
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley,150928
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi,150927
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude,150926

In [75]:
## renames axis
wine_reviews.rename_axis("wines", axis='rows').rename_axis("fields", axis='columns')

fields,country,description,designation,points,price,province,region_1,region_2,variety,winery,index_backwards
wines,,,,,,,,,,,
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz,150930
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez,150929
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley,150928
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi,150927
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude,150926
...,...,...,...,...,...,...,...,...,...,...,...
150925,Italy,Many people feel Fiano represents southern Ita...,NaN,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio,5
150926,France,"Offers an intriguing nose with ginger, lime an...",Cuvée Prestige,91,27.0,Champagne,Champagne,NaN,Champagne Blend,H.Germain,4
150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora,3
150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset,2
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder,1

### Combining

* pd.concat([dataset1, dataset2])
* left.join(right, lsuffix='_CAN', rsuffix='_UK')